### PR TITLE
Added a prop link field, Author Info, and a capacity charge descriptor

### PR DESCRIPTION
**Pull request by vincent-hebble**

### CODE REVIEW

**Comment by christophertull** [comment]
Thoughts on having respondent name/email/phone in the OWRS link that will be hosted on Github? Seems less-than-ideal to me. Do we have alternatives? 

image


cc @vincent-hebble @patwater

**Comment by patwater** [comment]
Hmmm so theoretically that's public information and should be fine as long as there's a disclaimer. Remember most staff person's email / phone number are listed publicly on their website. Maybe add some text to the effect of:

_"OWRS files stored publicly to easily enable corrections and comments from other member of the water community. The direct contact email and phone number of the point person on water rate information is helpful for analysts, researchers and others to follow up on data available here. If you do not have a point person or would not like to share that information, please feel free to share your districts general contact email and phone number."_

**Comment by christophertull** [comment]
FYI looks like version of the survey that is live right now (e.g. including billing units, etc) never got merged into master. So when @vincent-hebble started the most recent work you were working off of an outdated version of master (my fault for not merging in the changes).

I think I have effectively merged the two branches, so hopefully the river of time does not diverge again.

**Comment by christophertull** [comment]
Made a couple more minor tweaks including adding @patwater's disclaimer text

**Pull request merged**
