### PR TITLE
Updates to Commodity Charge still not finished

### PR DESCRIPTION
**Pull request by vincent-hebble**
I was able to get A Uniform rate mostly completed.

### CODE REVIEW

**Comment by vincent-hebble** [comment]
Finished up the Uniform Commodity Charge and the output is looking nice. The tiered and budget structure are going to be a little harder to get right but the framework is there, so hopefully that should get done a lot quicker. Hopefully it is looking good.

**Comment by vincent-hebble** [comment]
Also there is a minor javascript error when you select parameters for the first time, but everything works i just need to handle it

**Review by christophertull — COMMENTED** [review]
Looks solid dude! coming together really nicely :)

**Comment by vincent-hebble** [comment]
Got the tiered structure to work budget should come pretty easy considering it is much like tiered and that functionality is already prepared. Still need to regex inputs and some bugs do exist when changing some things but those are pretty easy to deal with just haven't got around to it. I also really need to comment the code I apologize for not doing that.

**Pull request merged**
